import { NestedArray } from "modal/index"
import { CiLocationOn } from "react-icons/ci"

export const dataCountry = [
    // # Việt Nam
    { city: "Hà Nội", code: "HAN" },
    { city: "Đà Nẵng", code: "DAD" },
    { city: "Hải Phòng", code: "HPH" },
    { city: "Quảng Ninh", code: "VDO" },
    { city: "Điện Biên Phủ", code: "DIN" },
    { city: "Hồ Chí Minh", code: "SGN" },
    { city: "Côn Đảo", code: "VCS" },
    { city: "Cần Thơ", code: "VCA" },
    { city: "Phú Quốc", code: "PQC" },
    { city: "Cà Mau", code: "CAH" },
    { city: "Kiên Giang", code: "VKG" },
    { city: "Nha Trang", code: "CXR" },
    { city: "Đà Lạt", code: "DLI" },
    { city: "TP.Vinh", code: "VII" },
    { city: "TP.Huế", code: "HUI" },
    { city: "Thanh Hóa", code: "THD" },
    { city: "Ban Mê Thuột", code: "BMV" },
    { city: "Gia Lai", code: "PXU" },
    { city: "Quy Nhơn", code: "UIH" },
    { city: "Đồng Hới", code: "VDH" },
    { city: "Tuy Hòa", code: "TBB" },
    { city: "Tam Kỳ", code: "VCL" },

    // # Châu Á
    { city: "Taipei", code: "TPE" },
    { city: "Taichung", code: "RMQ" },
    { city: "Kaohsiung", code: "KHH" },
    { city: "Tainan", code: "TNN" },
    { city: "Mumbai", code: "BOM" },
    { city: "Delhi", code: "DEL" },
    { city: "Kathmandu", code: "KTM" },
    { city: "Dhaka", code: "DAC" },
    { city: "Colombo", code: "CMB" },
    { city: "Kolkata", code: "CCU" },
    { city: "Istanbul", code: "SAW" },
    { city: "Dubai", code: "DXB" },

    // # Châu Âu
    { city: "Paris", code: "CDG" },
    { city: "London", code: "LGW" },
    { city: "Manchester", code: "MAN" },
    { city: "Frankfurt", code: "FRA" },
    { city: "Berlin", code: "SXF" },
    { city: "Amsterdam", code: "AMS" },
    { city: "Geneva", code: "GVA" },
    { city: "Prague", code: "PRG" },
    { city: "Rome", code: "FCO" },
    { city: "Vienna", code: "VIE" },
    { city: "Copenhagen", code: "CPH" },

    // # Hoa Kỳ - Canada
    { city: "New York", code: "NYC" },
    { city: "New York", code: "JFK" },
    { city: "Washington", code: "WAS" },
    { city: "Los Angeles", code: "LAX" },
    { city: "San Francisco", code: "SFO" },
    { city: "Atlanta", code: "ATL" },
    { city: "Boston", code: "BOS" },
    { city: "Chicago", code: "RFD" },
    { city: "Dallas", code: "DFW" },
    { city: "Denver", code: "DEN" },
    { city: "Honolulu", code: "HNL" },
    { city: "Miami", code: "MIA" },
    { city: "Minneapolis", code: "MSP" },
    { city: "Philadelphia", code: "PHL" },
    { city: "Portland", code: "PDX" },
    { city: "Seattle", code: "SEA" },
    { city: "St Louis", code: "STL" },
    { city: "Vancouver", code: "YVR" },
    { city: "Toronto", code: "YYZ" },
    { city: "Montreal", code: "XLM" },
    { city: "Ottawa", code: "YOW" },

    // # Châu Úc
    { city: "Melbourne", code: "MEL" },
    { city: "Sydney", code: "SYD" },
    { city: "Brisbane", code: "BNE" },
    { city: "Perth", code: "PER" },
    { city: "Adelaide", code: "ADL" },
    { city: "Auckland", code: "AKL" },
    { city: "Wellington", code: "WLG" },

    // # Châu Phi
    { city: "Madrid", code: "MAD" },
    { city: "Moscow", code: "MOW" },
    { city: "Nairobi", code: "NBO" },
    { city: "Maputo", code: "MPM" },
    { city: "Luanda", code: "LAD" },
    { city: "Johannesburg", code: "JNB" },
    { city: "Cape Town", code: "CPT" },
    { city: "Dar Es Salaam", code: "DAR" }
]

export const data = [
    {
        Adt: 1,
        Airline: "VJ2",
        AirlineOperating: "VJ",
        AirlineType: null,
        Chd: 0,
        Currency: "VND",
        Duration: 130,
        DurationFormat: "02h 10p",
        EndDate: "01-10-2023",
        EndPoint: "SGN",
        EndTime: "07:20",
        FareAdt: 109000,
        FareAdtFormat: "109,000",
        FareAdtFull: 702120,
        FareAdtFullFormat: "702,120",
        FareBasis: "",
        FareChd: 0,
        FareChdFormat: "0",
        FareChdFull: 0,
        FareChdFullFormat: "0",
        FareDataId: 0,
        FareInf: 0,
        FareInfFormat: "0",
        FareInfFull: 0,
        FareInfFullFormat: "0",
        FlightId: 0,
        FlightNumber: "VJ199",
        FlightValue: "0VJ199E1_ECOHANSGN202310010510",
        Id: "DM0VJHANSGN0110231000637360",
        Inf: 0,
        IsSelect: false,
        Leg: 0,
        ListSegment: [
            {
                Airline: "VJ",
                AllowanceBaggage: " 0 Kg",
                Cabin: "Economy",
                Class: "E1_ECO",
                Duration: "02h 10p",
                EndDate: "01-10-2023",
                EndPoint: "SGN",
                EndTime: "07:20",
                FlightNumber: "VJ199",
                HandBaggage: "7kg",
                Id: 0,
                Plane: "320",
                StartDate: "01-10-2023",
                StartPoint: "HAN",
                StartTime: "05:10"
            }
        ],
        Promo: false,
        Session: "DM0VJHANSGN011023100063736",
        StartDate: "01-10-2023",
        StartPoint: "HAN",
        StartTime: "05:10",
        TotalFareAdt: 702120,
        TotalFareAdtFormat: "702,120",
        TotalFareChd: 0,
        TotalFareChdFormat: "0",
        TotalFareInf: 0,
        TotalFareInfFormat: "0",
        TotalFeeTaxAdt: 593120,
        TotalFeeTaxAdtFormat: "593,120",
        TotalFeeTaxChd: 0,
        TotalFeeTaxChdFormat: "0",
        TotalFeeTaxInf: 0,
        TotalFeeTaxInfFormat: "0",
        TotalPrice: 702120,
        TotalPriceFormat: "702,120"
    },
    {
        Adt: 1,
        Airline: "VJ",
        AirlineOperating: "VJ",
        AirlineType: null,
        Chd: 0,
        Currency: "VND",
        Duration: 130,
        DurationFormat: "02h 10p",
        EndDate: "01-10-2023",
        EndPoint: "SGN",
        EndTime: "07:20",
        FareAdt: 109000,
        FareAdtFormat: "109,000",
        FareAdtFull: 702120,
        FareAdtFullFormat: "702,120",
        FareBasis: "",
        FareChd: 0,
        FareChdFormat: "0",
        FareChdFull: 0,
        FareChdFullFormat: "0",
        FareDataId: 0,
        FareInf: 0,
        FareInfFormat: "0",
        FareInfFull: 0,
        FareInfFullFormat: "0",
        FlightId: 0,
        FlightNumber: "VJ199",
        FlightValue: "0VJ199E1_ECOHANSGN202310010510",
        Id: "DM0VJHANSGN0110231000637360",
        Inf: 0,
        IsSelect: false,
        Leg: 0,
        ListSegment: [
            {
                Airline: "VJ",
                AllowanceBaggage: " 0 Kg",
                Cabin: "Economy Flex",
                Class: "E1_ECO",
                Duration: "02h 10p",
                EndDate: "01-10-2023",
                EndPoint: "SGN",
                EndTime: "07:20",
                FlightNumber: "VJ199",
                HandBaggage: "7kg",
                Id: 0,
                Plane: "320",
                StartDate: "01-10-2023",
                StartPoint: "HAN",
                StartTime: "05:10"
            }
        ],
        Promo: false,
        Session: "DM0VJHANSGN011023100063736",
        StartDate: "01-10-2023",
        StartPoint: "HAN",
        StartTime: "05:10",
        TotalFareAdt: 702120,
        TotalFareAdtFormat: "702,120",
        TotalFareChd: 0,
        TotalFareChdFormat: "0",
        TotalFareInf: 0,
        TotalFareInfFormat: "0",
        TotalFeeTaxAdt: 593120,
        TotalFeeTaxAdtFormat: "593,120",
        TotalFeeTaxChd: 0,
        TotalFeeTaxChdFormat: "0",
        TotalFeeTaxInf: 0,
        TotalFeeTaxInfFormat: "0",
        TotalPrice: 702120,
        TotalPriceFormat: "702,120"
    },
    {
        Adt: 1,
        Airline: "VJ",
        AirlineOperating: "VJ",
        AirlineType: null,
        Chd: 0,
        Currency: "VND",
        Duration: 130,
        DurationFormat: "02h 10p",
        EndDate: "01-10-2023",
        EndPoint: "SGN",
        EndTime: "07:20",
        FareAdt: 109000,
        FareAdtFormat: "109,000",
        FareAdtFull: 702120,
        FareAdtFullFormat: "702,120",
        FareBasis: "",
        FareChd: 0,
        FareChdFormat: "0",
        FareChdFull: 0,
        FareChdFullFormat: "0",
        FareDataId: 0,
        FareInf: 0,
        FareInfFormat: "0",
        FareInfFull: 0,
        FareInfFullFormat: "0",
        FlightId: 0,
        FlightNumber: "VJ199",
        FlightValue: "0VJ199E1_ECOHANSGN202310010510",
        Id: "DM0VJHANSGN0110231000637360",
        Inf: 0,
        IsSelect: false,
        Leg: 0,
        ListSegment: [
            {
                Airline: "VJ",
                AllowanceBaggage: " 0 Kg",
                Cabin: "Economy",
                Class: "E1_ECO",
                Duration: "02h 10p",
                EndDate: "01-10-2023",
                EndPoint: "SGN",
                EndTime: "07:20",
                FlightNumber: "VJ199",
                HandBaggage: "7kg",
                Id: 0,
                Plane: "320",
                StartDate: "01-10-2023",
                StartPoint: "HAN",
                StartTime: "05:10"
            }
        ],
        Promo: false,
        Session: "DM0VJHANSGN011023100063736",
        StartDate: "01-10-2023",
        StartPoint: "HAN",
        StartTime: "05:10",
        TotalFareAdt: 702120,
        TotalFareAdtFormat: "702,120",
        TotalFareChd: 0,
        TotalFareChdFormat: "0",
        TotalFareInf: 0,
        TotalFareInfFormat: "0",
        TotalFeeTaxAdt: 593120,
        TotalFeeTaxAdtFormat: "593,120",
        TotalFeeTaxChd: 0,
        TotalFeeTaxChdFormat: "0",
        TotalFeeTaxInf: 0,
        TotalFeeTaxInfFormat: "0",
        TotalPrice: 702120,
        TotalPriceFormat: "702,120"
    }
]

export const mapOption: NestedArray = [
    {
        id: 1,
        label: 'Việt Nam',
        children: [
            { key: "Việt Nam", unsigned:'Da Nang', label: "Đà Nẵng", value: "DAD", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Ho Chi Minh', label: "Hồ Chí Minh", value: "SGN", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Hai Phong', label: "Hải Phòng", value: "HPH", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Ha Noi', label: "Hà Nội", value: "HAN", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Quang Ninh', label: "Quảng Ninh", value: "VDO", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Con Dao', label: "Côn Đảo", value: "VCS", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Can Tho', label: "Cần Thơ", value: "VCA", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Phu Quoc', label: "Phú Quốc", value: "PQC", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Ca Mau', label: "Cà Mau", value: "CAH", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Kien Giang', label: "Kiên Giang", value: "VKG", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Nha Trang', label: "Nha Trang", value: "CXR", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Da Lat', label: "Đà Lạt", value: "DLI", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Vinh', label: "Vinh", value: "VII", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Hue', label: "Huế", value: "HUI", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Thanh Hoa', label: "Thanh Hóa", value: "THD", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Ban Me Thuot', label: "Ban Mê Thuột", value: "BMV", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Gia Lai', label: "Gia Lai", value: "PXU", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Quy Nhon', label: "Quy Nhơn", value: "UIH", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Dong Hoi', label: "Đồng Hới", value: "VDH", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Tuy Hoa', label: "Tuy Hòa", value: "TBB", icon: <CiLocationOn /> },
            { key: "Việt Nam", unsigned:'Tam Ky', label: "Tam Kỳ", value: "VCL", icon: <CiLocationOn /> },
        ]
    }
    ,
    {
        id: 2,
        label: 'Châu Á',
        children:     [
            { key: "Châu Á", unsigned:'Taipei', label: "Taipei", value: "TPE", icon: <CiLocationOn /> },
            { key: "Châu Á", unsigned:'Taichung', label: "Taichung", value: "RMQ", icon: <CiLocationOn /> },
            { key: "Châu Á", unsigned:'Kaohsiung', label: "Kaohsiung", value: "KHH", icon: <CiLocationOn /> },
            { key: "Châu Á", unsigned:'Tainan', label: "Tainan", value: "TNN", icon: <CiLocationOn /> },
            { key: "Châu Á", unsigned:'Mumbai', label: "Mumbai", value: "BOM", icon: <CiLocationOn /> },
            { key: "Châu Á", unsigned:'Delhi', label: "Delhi", value: "DEL", icon: <CiLocationOn /> },
            { key: "Châu Á", unsigned:'Kathmandu', label: "Kathmandu", value: "KTM", icon: <CiLocationOn /> },
            { key: "Châu Á", unsigned:'Dhaka', label: "Dhaka", value: "DAC", icon: <CiLocationOn /> },
            { key: "Châu Á", unsigned:'Colombo', label: "Colombo", value: "CMB", icon: <CiLocationOn /> },
            { key: "Châu Á", unsigned:'Kolkata', label: "Kolkata", value: "CCU", icon: <CiLocationOn /> },
            { key: "Châu Á", unsigned:'Istanbul', label: "Istanbul", value: "SAW", icon: <CiLocationOn /> },
            { key: "Châu Á", unsigned:'Dubai', label: "Dubai", value: "DXB", icon: <CiLocationOn /> },
        ]
    },
    {
        id: 3,
        label: 'Châu Âu',
        children: [
            { key: "Châu Âu", unsigned:'Paris', label: "Paris", value: "CDG", icon: <CiLocationOn /> },
            { key: "Châu Âu", unsigned:'London', label: "London", value: "LGW", icon: <CiLocationOn /> },
            { key: "Châu Âu", unsigned:'Manchester', label: "Manchester", value: "MAN", icon: <CiLocationOn /> },
            { key: "Châu Âu", unsigned:'Frankfurt', label: "Frankfurt", value: "FRA", icon: <CiLocationOn /> },
            { key: "Châu Âu", unsigned:'Berlin', label: "Berlin", value: "SXF", icon: <CiLocationOn /> },
            { key: "Châu Âu", unsigned:'Amsterdam', label: "Amsterdam", value: "AMS", icon: <CiLocationOn /> },
            { key: "Châu Âu", unsigned:'Geneva', label: "Geneva", value: "GVA", icon: <CiLocationOn /> },
            { key: "Châu Âu", unsigned:'Prague', label: "Prague", value: "PRG", icon: <CiLocationOn /> },
            { key: "Châu Âu", unsigned:'Rome', label: "Rome", value: "FCO", icon: <CiLocationOn /> },
            { key: "Châu Âu", unsigned:'Vienna', label: "Vienna", value: "VIE", icon: <CiLocationOn /> },
            { key: "Châu Âu", unsigned:'Copenhagen', label: "Copenhagen", value: "CPH", icon: <CiLocationOn /> }
        ]
    },
    {
        id: 4,
        label: 'Hoa Kỳ - Canada',
        children: [
            { key: "Hoa Kỳ - Canada", unsigned:'New York', label: "New York", value: "NYC", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Washington', label: "Washington", value: "WAS", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Los Angeles', label: "Los Angeles", value: "LAX", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'San Francisco', label: "San Francisco", value: "SFO", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Atlanta', label: "Atlanta", value: "ATL", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Boston', label: "Boston", value: "BOS", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Chicago', label: "Chicago", value: "RFD", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Dallas', label: "Dallas", value: "DFW", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Denver', label: "Denver", value: "DEN", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Honolulu', label: "Honolulu", value: "HNL", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Miami', label: "Miami", value: "MIA", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Minneapolis', label: "Minneapolis", value: "MSP", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Philadelphia', label: "Philadelphia", value: "PHL", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Portland', label: "Portland", value: "PDX", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Seattle', label: "Seattle", value: "SEA", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'St Louis', label: "St Louis", value: "STL", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Vancouver', label: "Vancouver", value: "YVR", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Toronto', label: "Toronto", value: "YYZ", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Montreal', label: "Montreal", value: "XLM", icon: <CiLocationOn /> },
            { key: "Hoa Kỳ - Canada", unsigned:'Ottawa', label: "Ottawa", value: "YOW", icon: <CiLocationOn /> }
        ]
    },
    {
        id: 5,
        label: 'Châu Úc',
        children: [
            { key: "Châu Úc", unsigned:'Melbourne', label: "Melbourne", value: "MEL", icon: <CiLocationOn /> },
            { key: "Châu Úc", unsigned:'Sydney', label: "Sydney", value: "SYD", icon: <CiLocationOn /> },
            { key: "Châu Úc", unsigned:'Brisbane', label: "Brisbane", value: "BNE", icon: <CiLocationOn /> },
            { key: "Châu Úc", unsigned:'Perth', label: "Perth", value: "PER", icon: <CiLocationOn /> },
            { key: "Châu Úc", unsigned:'Adelaide', label: "Adelaide", value: "ADL", icon: <CiLocationOn /> },
            { key: "Châu Úc", unsigned:'Auckland', label: "Auckland", value: "AKL", icon: <CiLocationOn /> },
            { key: "Châu Úc", unsigned:'Wellington', label: "Wellington", value: "WLG", icon: <CiLocationOn /> }
        ]
    },
    {
        id: 6,
        label: 'Châu Phi',
        children: [
            { key: "Châu Phi", unsigned:'Madrid', label: "Madrid", value: "MAD", icon: <CiLocationOn /> },
            { key: "Châu Phi", unsigned:'Moscow', label: "Moscow", value: "MOW", icon: <CiLocationOn /> },
            { key: "Châu Phi", unsigned:'Nairobi', label: "Nairobi", value: "NBO", icon: <CiLocationOn /> },
            { key: "Châu Phi", unsigned:'Maputo', label: "Maputo", value: "MPM", icon: <CiLocationOn /> },
            { key: "Châu Phi", unsigned:'Luanda', label: "Luanda", value: "LAD", icon: <CiLocationOn /> },
            { key: "Châu Phi", unsigned:'Johannesburg', label: "Johannesburg", value: "JNB", icon: <CiLocationOn /> },
            { key: "Châu Phi", unsigned:'Cape Town', label: "Cape Town", value: "CPT", icon: <CiLocationOn /> },
            { key: "Châu Phi", unsigned:'Dar Es Salaam', label: "Dar Es Salaam", value: "DAR", icon: <CiLocationOn /> }
        ]
    },
]